# Generated by Django 5.1.15 on 2026-09-27 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_tubos_de_toma"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(unique=True, verbose_name="Día")),
                (
                    "last_value",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Último valor usado"
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia de órdenes",
                "verbose_name_plural": "Secuencias de órdenes",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=11,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REGISTRADA", "Registrada"),
                            ("MUESTRA_TOMADA", "Muestra tomada"),
                            ("EN_PROCESO", "En proceso"),
                            ("RESULTADOS_CARGADOS", "Resultados cargados"),
                            ("VALIDADA", "Validada"),
                            ("ENTREGADA", "Entregada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="REGISTRADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("URGENTE", "Urgente")],
                        default="NORMAL",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                ("ordered_at", models.DateTimeField(verbose_name="Registrada el")),
                (
                    "requested_by",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Médico solicitante",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observaciones"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Talla (cm)",
                    ),
                ),
                (
                    "urine_volume_24h_ml",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="Volumen de orina 24 h (mL)",
                    ),
                ),
                (
                    "price_list_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Lista de precios",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, default="", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Descuentos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
                (
                    "converted_currency_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=3,
                        verbose_name="Moneda de referencia",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="Tasa",
                    ),
                ),
                (
                    "converted_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Total en moneda de referencia",
                    ),
                ),
                (
                    "quote_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Detalle de la cotización",
                    ),
                ),
                (
                    "pricing_pending",
                    models.BooleanField(
                        default=False,
                        help_text="La lista no tenía precio para algún examen al registrar la orden.",
                        verbose_name="Precio pendiente",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Pagada")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pagada el"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Anulada el"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Motivo de anulación",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Anulada por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cobrada por",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Órdenes",
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROCESO", "En proceso"),
                            ("CARGADO", "Cargado"),
                            ("VALIDADO", "Validado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.profile",
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.test",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen de la orden",
                "verbose_name_plural": "Exámenes de la orden",
                "ordering": ["order", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "sequence",
                    models.PositiveSmallIntegerField(verbose_name="Secuencia"),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=14,
                        unique=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Código de barras",
                    ),
                ),
                (
                    "collection_label",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Toma"
                    ),
                ),
                (
                    "is_exclusive",
                    models.BooleanField(
                        default=False,
                        help_text="No recibe exámenes de otros requisitos.",
                        verbose_name="Tubo propio",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Por tomar"),
                            ("TOMADA", "Tomada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tomada el"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rechazada el"
                    ),
                ),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Motivo de rechazo",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tomada por",
                    ),
                ),
                (
                    "container_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="samples",
                        to="catalog.containertype",
                        verbose_name="Tubo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="orders.order",
                    ),
                ),
                (
                    "order_items",
                    models.ManyToManyField(
                        related_name="samples",
                        to="orders.orderitem",
                        verbose_name="Exámenes",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Rechazada por",
                    ),
                ),
                (
                    "replaces",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replaced_by",
                        to="orders.sample",
                        verbose_name="Reemplaza a",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muestra",
                "verbose_name_plural": "Muestras",
                "ordering": ["order", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="LabelPrint",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_reprint",
                    models.BooleanField(default=False, verbose_name="Reimpresión"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prints",
                        to="orders.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impresión de etiqueta",
                "verbose_name_plural": "Impresiones de etiquetas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "ordered_at"], name="orders_orde_status_9cd221_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "test"), name="orderitem_unique_test"
            ),
        ),
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("order", "sequence"), name="sample_unique_sequence"
            ),
        ),
    ]
