# Generated by Django 5.1.15 on 2026-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="patient_condition",
            field=models.CharField(
                choices=[("NINGUNA", "Ninguna"), ("EMBARAZO", "Embarazo")],
                default="NINGUNA",
                max_length=10,
                verbose_name="Condición del paciente",
            ),
        ),
    ]
