# Generated by Django 5.1.15 on 2026-09-20 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ADMIN_LAB', 'Administrador del laboratorio'), ('BIOANALISTA', 'Bioanalista'), ('TECNICO', 'Técnico'), ('RECEPCION', 'Recepción'), ('FACTURACION', 'Facturación'), ('SOLO_LECTURA', 'Sólo lectura')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='Permisos')),
                ('is_system', models.BooleanField(default=True, verbose_name='Rol del sistema')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Membresía',
                'verbose_name_plural': 'Membresías',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
