# Generated by Django 5.1.15 on 2026-09-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_admin_log_por_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="professional_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Se imprime bajo la firma, p. ej. «Lcda. en Bioanálisis».",
                max_length=60,
                verbose_name="Título profesional",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="firmas/",
                verbose_name="Firma (imagen)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stamp_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="firmas/",
                verbose_name="Sello (imagen)",
            ),
        ),
    ]
