# Generated by Django 5.1.15 on 2026-09-28 17:23

from django.db import migrations, models


def add_auxiliar_role(apps, schema_editor):
    """Rol «Auxiliar de toma» en los laboratorios existentes (mismo pk que el fixture)."""
    Role = apps.get_model("accounts", "Role")
    if not Role.objects.filter(code="AUXILIAR_TOMA").exists():
        Role.objects.update_or_create(pk=7, defaults={
            "code": "AUXILIAR_TOMA", "name": "Auxiliar de toma de muestras",
            "permissions": {"puede_validar_resultados": False,
                            "puede_gestionar_usuarios": False, "puede_facturar": False},
            "is_system": True})


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_firma_y_sello"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="Debe cambiar la clave"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.CharField(
                choices=[
                    ("ADMIN_LAB", "Administrador del laboratorio"),
                    ("BIOANALISTA", "Bioanalista"),
                    ("TECNICO", "Técnico"),
                    ("RECEPCION", "Recepción"),
                    ("FACTURACION", "Facturación"),
                    ("SOLO_LECTURA", "Sólo lectura"),
                    ("AUXILIAR_TOMA", "Auxiliar de toma de muestras"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RunPython(add_auxiliar_role, migrations.RunPython.noop),
    ]
