# Generated by Django 5.1.15 on 2026-09-26 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_profiles_y_sin_precio_en_test"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Código ISO 4217"
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Nombre")),
                ("symbol", models.CharField(max_length=8, verbose_name="Símbolo")),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Decimales"
                    ),
                ),
                (
                    "is_base",
                    models.BooleanField(default=False, verbose_name="Moneda base"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "ordering": ["order_index", "code"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("PERCENT", "Porcentaje"),
                            ("FIXED_AMOUNT", "Monto fijo"),
                        ],
                        max_length=15,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Valor"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("ORDER", "Toda la orden"),
                            ("ITEM", "Por examen/perfil"),
                        ],
                        max_length=10,
                        verbose_name="Alcance",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente desde"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente hasta"
                    ),
                ),
                (
                    "is_stackable",
                    models.BooleanField(
                        default=False, verbose_name="Acumulable con otros"
                    ),
                ),
                (
                    "requires_authorization",
                    models.BooleanField(
                        default=False, verbose_name="Requiere autorización"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notas"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discounts",
                        to="billing.currency",
                        verbose_name="Moneda (monto fijo)",
                    ),
                ),
                (
                    "profiles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="catalog.profile",
                        verbose_name="Perfiles",
                    ),
                ),
                (
                    "tests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="catalog.test",
                        verbose_name="Exámenes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento",
                "verbose_name_plural": "Descuentos",
                "ordering": ["order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8, max_digits=20, verbose_name="Tasa"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Vigente desde")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Carga manual"),
                            ("BCV", "Banco Central de Venezuela"),
                            ("OTRO", "Otra fuente"),
                        ],
                        default="MANUAL",
                        max_length=10,
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Notas"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_from",
                        to="billing.currency",
                        verbose_name="De",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_to",
                        to="billing.currency",
                        verbose_name="A",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasa de cambio",
                "verbose_name_plural": "Tasas de cambio",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Predeterminada"),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente desde"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vigente hasta"
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notas"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_lists",
                        to="billing.currency",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de precios",
                "verbose_name_plural": "Listas de precios",
                "ordering": ["order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "pricing_mode",
                    models.CharField(
                        choices=[
                            ("FIXED", "Precio fijo"),
                            ("SUM_WITH_DISCOUNT", "Suma de exámenes menos %"),
                        ],
                        default="FIXED",
                        max_length=20,
                        verbose_name="Modo de precio",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "profile_discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="% de descuento del perfil",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.pricelist",
                        verbose_name="Lista",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_items",
                        to="catalog.profile",
                        verbose_name="Perfil",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_items",
                        to="catalog.test",
                        verbose_name="Examen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio",
                "verbose_name_plural": "Precios",
                "ordering": ["price_list", "order_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="currency",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_base", True)),
                fields=("is_base",),
                name="currency_single_base",
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)), name="discount_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "PERCENT"), _negated=True),
                    ("value__lte", 100),
                    _connector="OR",
                ),
                name="discount_percent_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "FIXED_AMOUNT"), _negated=True),
                    ("currency__isnull", False),
                    _connector="OR",
                ),
                name="discount_fixed_requires_currency",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("from_currency", "to_currency", "effective_date"),
                name="exchangerate_unique_pair_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)), name="exchangerate_rate_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_currency", models.F("to_currency")), _negated=True
                ),
                name="exchangerate_distinct_currencies",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="pricelist_single_default",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_until__isnull", True),
                    ("valid_from__lte", models.F("valid_until")),
                    _connector="OR",
                ),
                name="pricelist_valid_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("test__isnull", False), ("profile__isnull", True)),
                    models.Q(("test__isnull", True), ("profile__isnull", False)),
                    _connector="OR",
                ),
                name="pricelistitem_test_xor_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("test__isnull", False)),
                fields=("price_list", "test"),
                name="pricelistitem_unique_test",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("profile__isnull", False)),
                fields=("price_list", "profile"),
                name="pricelistitem_unique_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("pricing_mode", "FIXED"), _negated=True),
                    ("price__isnull", False),
                    _connector="OR",
                ),
                name="pricelistitem_fixed_requires_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("pricing_mode", "SUM_WITH_DISCOUNT"), _negated=True),
                    models.Q(
                        ("profile__isnull", False),
                        ("profile_discount_percent__gte", 0),
                        ("profile_discount_percent__lte", 100),
                    ),
                    _connector="OR",
                ),
                name="pricelistitem_sum_mode_only_profiles_with_percent",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price__isnull", True), ("price__gte", 0), _connector="OR"
                ),
                name="pricelistitem_price_non_negative",
            ),
        ),
    ]
