# Generated by Django 5.1.15 on 2026-09-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('state', models.CharField(max_length=80, verbose_name='Estado')),
                ('municipality', models.CharField(blank=True, default='', max_length=120, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ['state', 'name'],
                'unique_together': {('name', 'state')},
            },
        ),
    ]
