# Generated by Django 5.1.15 on 2026-09-19 19:23

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio mensual')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('max_users', models.PositiveIntegerField(default=0, verbose_name='Máx. usuarios (0 = ilimitado)')),
                ('max_orders_month', models.PositiveIntegerField(default=0, verbose_name='Máx. órdenes/mes')),
                ('max_storage_mb', models.PositiveIntegerField(default=0, verbose_name='Máx. almacenamiento (MB)')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='Características')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible en precios')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del laboratorio')),
                ('legal_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Razón social')),
                ('rif', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RIF')),
                ('status', models.CharField(choices=[('DEMO', 'Demo'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('MOROSO', 'Moroso'), ('CANCELADO', 'Cancelado')], default='DEMO', max_length=20)),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('paid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Laboratorio',
                'verbose_name_plural': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('TRIAL', 'Prueba'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], default='TRIAL', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
            },
        ),
    ]
