# Generated by Django 5.1.15 on 2026-09-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_brand_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Mostrar la firma de Biolife en los informes",
                    ),
                ),
                (
                    "report_brand_text",
                    models.CharField(
                        default="Generado con Biolife · Sistema de gestión para laboratorios clínicos",
                        max_length=160,
                        verbose_name="Texto al pie del informe",
                    ),
                ),
                (
                    "report_brand_contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono, Instagram o web; se imprime junto al texto.",
                        max_length=160,
                        verbose_name="Contacto de Biolife (opcional)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de la plataforma",
                "verbose_name_plural": "Configuración de la plataforma",
            },
        ),
    ]
