# Generated by Django 5.1.15 on 2026-09-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Banner')),
                ('color_primary', models.CharField(default='#1B5FA8', max_length=7, verbose_name='Color primario')),
                ('color_secondary', models.CharField(blank=True, default='', max_length=7, verbose_name='Color secundario')),
                ('report_header_html', models.TextField(blank=True, default='', verbose_name='Cabecera del informe')),
                ('report_footer_text', models.TextField(blank=True, default='', verbose_name='Pie del informe')),
                ('report_disclaimer', models.TextField(blank=True, default='', verbose_name='Descargo de responsabilidad')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, default='', verbose_name='Sitio web')),
                ('timezone', models.CharField(default='America/Caracas', max_length=50, verbose_name='Zona horaria')),
                ('time_format', models.CharField(choices=[('H12', '12 horas'), ('H24', '24 horas')], default='H12', max_length=3)),
                ('date_format', models.CharField(default='dd/MM/yyyy', max_length=20, verbose_name='Formato de fecha')),
                ('decimal_separator', models.CharField(choices=[('COMA', 'Coma'), ('PUNTO', 'Punto')], default='COMA', max_length=5)),
                ('order_number_prefix', models.CharField(blank=True, default='', max_length=10)),
                ('order_number_next', models.PositiveIntegerField(default=1)),
                ('require_second_validation', models.BooleanField(default=False, verbose_name='Requiere doble validación')),
            ],
            options={
                'verbose_name': 'Configuración del laboratorio',
                'verbose_name_plural': 'Configuración del laboratorio',
            },
        ),
    ]
