# Generated by Django 5.1.15 on 2026-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='decimal_separator',
            field=models.CharField(choices=[('COMA', 'Coma'), ('PUNTO', 'Punto')], default='COMA', max_length=5, verbose_name='Separador decimal'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='order_number_next',
            field=models.PositiveIntegerField(default=1, verbose_name='Próximo número de orden'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='order_number_prefix',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Prefijo de número de orden'),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='time_format',
            field=models.CharField(choices=[('H12', '12 horas'), ('H24', '24 horas')], default='H12', max_length=3, verbose_name='Formato de hora'),
        ),
    ]
