# Generated by Django 5.1.15 on 2026-09-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_lab', '0002_alter_tenantsettings_decimal_separator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='lab_initials',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Siglas del laboratorio'),
        ),
    ]
