# Generated by Django 5.1.15 on 2026-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_lab", "0003_tenantsettings_lab_initials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantsettings",
            name="order_number_next",
        ),
        migrations.RemoveField(
            model_name="tenantsettings",
            name="order_number_prefix",
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="label_extra_for_order",
            field=models.BooleanField(
                default=False,
                help_text="Imprime una etiqueta más, con el número de orden, para pegar en la solicitud.",
                verbose_name="Etiqueta extra para la hoja de la orden",
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="label_height_mm",
            field=models.PositiveSmallIntegerField(
                default=25, verbose_name="Alto de etiqueta (mm)"
            ),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="label_width_mm",
            field=models.PositiveSmallIntegerField(
                default=50, verbose_name="Ancho de etiqueta (mm)"
            ),
        ),
    ]
