# Generated by Django 5.1.15 on 2026-09-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_lab", "0004_etiquetas_y_numero_diario"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="report_link_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Pasado este plazo, la página de verificación sigue confirmando el informe pero ya no permite descargarlo.",
                verbose_name="Días que el PDF se puede descargar desde el QR",
            ),
        ),
    ]
