# Generated by Django 5.1.15 on 2026-09-26 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Último valor usado')),
            ],
            options={
                'verbose_name': 'Secuencia de código de paciente',
                'verbose_name_plural': 'Secuencias de código de paciente',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('document_type', models.CharField(choices=[('V', 'Cédula V'), ('E', 'Cédula E'), ('J', 'RIF Jurídico'), ('P', 'Pasaporte')], max_length=1, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'unique_together': {('document_type', 'document_number')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('internal_code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código interno')),
                ('document_type', models.CharField(choices=[('V', 'Cédula V'), ('E', 'Cédula E'), ('J', 'RIF Jurídico'), ('P', 'Pasaporte'), ('SIN_DOCUMENTO', 'Sin documento')], max_length=15, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de documento')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('declared_age_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad declarada')),
                ('declared_age_unit', models.CharField(blank=True, choices=[('DIAS', 'Días'), ('MESES', 'Meses'), ('ANOS', 'Años')], default='', max_length=5, verbose_name='Unidad de edad declarada')),
                ('declared_age_at', models.DateField(blank=True, null=True, verbose_name='Fecha en que se declaró la edad')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.locality', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='PatientGuardian',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('relationship', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('HERMANO', 'Hermano/a'), ('TUTOR_LEGAL', 'Tutor legal'), ('OTRO', 'Otro')], max_length=15, verbose_name='Parentesco')),
                ('relationship_detail', models.CharField(blank=True, default='', max_length=100, verbose_name='Detalle del parentesco')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Representante principal')),
                ('legal_doc_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia de documento legal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='patients.guardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Representante de paciente',
                'verbose_name_plural': 'Representantes de pacientes',
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number__isnull', False)), fields=('document_type', 'document_number'), name='uniq_patient_document'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('birth_date__isnull', False), ('declared_age_value__isnull', False), _connector='OR'), name='patient_has_birth_date_or_declared_age'),
        ),
        migrations.AlterUniqueTogether(
            name='patientguardian',
            unique_together={('patient', 'guardian')},
        ),
    ]
