# Generated by Django 5.1.15 on 2026-09-28 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_observaciones_predefinidas"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Antecedent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "suggested_parameters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to="catalog.parameter",
                        verbose_name="Parámetros a vigilar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antecedente",
                "verbose_name_plural": "Antecedentes",
                "ordering": ["order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="PatientAntecedent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Nota"
                    ),
                ),
                (
                    "antecedent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="patients.antecedent",
                        verbose_name="Antecedente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedents",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antecedente del paciente",
                "verbose_name_plural": "Antecedentes del paciente",
                "ordering": ["antecedent__order_index", "antecedent__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("patient", "antecedent"),
                        name="patientantecedent_unique",
                    )
                ],
            },
        ),
    ]
