# Generated by Django 5.1.15 on 2026-09-28 02:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0003_entrega"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("version", models.PositiveSmallIntegerField(verbose_name="Versión")),
                (
                    "kind",
                    models.CharField(
                        choices=[("PARCIAL", "Parcial"), ("FINAL", "Final")],
                        max_length=8,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VIGENTE", "Vigente"),
                            ("REEMPLAZADO", "Reemplazado"),
                        ],
                        default="VIGENTE",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Contenido congelado")),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="Huella SHA-256"),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Huella de la versión anterior",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="Código de verificación",
                    ),
                ),
                (
                    "replaced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reemplazado el"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="orders.order",
                        verbose_name="Orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe",
                "verbose_name_plural": "Informes",
                "ordering": ["order", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "version"), name="report_unique_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "VIGENTE")),
                        fields=("order",),
                        name="report_one_current_per_order",
                    ),
                ],
            },
        ),
    ]
