# Generated by Django 5.1.15 on 2026-09-26 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodedOptionSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Conjunto de opciones',
                'verbose_name_plural': 'Conjuntos de opciones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Método',
                'verbose_name_plural': 'Métodos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('print_page_break', models.BooleanField(default=False, verbose_name='Salto de página al imprimir')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('sample_type', models.CharField(choices=[('SANGRE_TOTAL', 'Sangre total'), ('SUERO', 'Suero'), ('PLASMA', 'Plasma'), ('ORINA', 'Orina'), ('ORINA_24H', 'Orina 24 horas'), ('HECES', 'Heces'), ('OTRO', 'Otro')], max_length=15, verbose_name='Tipo de muestra')),
                ('container', models.CharField(blank=True, default='', max_length=100, verbose_name='Contenedor')),
                ('process_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de proceso')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
                ('requires_fasting', models.BooleanField(default=False, verbose_name='Requiere ayuno')),
                ('requires_anthropometry', models.BooleanField(default=False, verbose_name='Requiere datos antropométricos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='catalog.method')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='catalog.section')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['section__order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_groups', to='catalog.test')),
            ],
            options={
                'verbose_name': 'Grupo de parámetros',
                'verbose_name_plural': 'Grupos de parámetros',
                'ordering': ['test', 'order_index'],
                'unique_together': {('test', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('symbol', models.CharField(max_length=20, unique=True, verbose_name='Símbolo')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='CodedOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('value', models.CharField(max_length=150, verbose_name='Valor')),
                ('ordinal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Orden clínico')),
                ('numeric_equivalent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Equivalente numérico')),
                ('is_pathological', models.BooleanField(default=False, verbose_name='Marca resultado patológico')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Orden de presentación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('option_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='catalog.codedoptionset')),
            ],
            options={
                'verbose_name': 'Opción codificada',
                'verbose_name_plural': 'Opciones codificadas',
                'ordering': ['option_set', 'order_index'],
                'unique_together': {('option_set', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('value_type', models.CharField(choices=[('NUMERIC', 'Numérico'), ('NUMERIC_CALCULATED', 'Numérico calculado'), ('CODED', 'Codificado'), ('SEMIQUANTITATIVE', 'Semicuantitativo'), ('QUALITATIVE', 'Cualitativo'), ('TITER', 'Título/dilución'), ('COUNT_RANGE', 'Rango de conteo'), ('NARRATIVE', 'Narrativo'), ('MULTI_CATALOG', 'Catálogo multi-selección')], max_length=20, verbose_name='Tipo de valor')),
                ('decimals', models.PositiveSmallIntegerField(default=2, verbose_name='Decimales')),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('formula', models.TextField(blank=True, default='', verbose_name='Fórmula')),
                ('is_printable', models.BooleanField(default=True, verbose_name='Se imprime en el informe')),
                ('is_optional', models.BooleanField(default=False, verbose_name='Opcional (puede quedar en blanco)')),
                ('instrument_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Código del instrumento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='depended_by', to='catalog.parameter')),
                ('option_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='catalog.codedoptionset')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='catalog.parametergroup')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='catalog.test')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='catalog.unit')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['test', 'group__order_index', 'order_index'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('value_type__in', ('CODED', 'SEMIQUANTITATIVE', 'QUALITATIVE', 'TITER', 'MULTI_CATALOG')), ('option_set__isnull', False)), models.Q(('value_type__in', ('CODED', 'SEMIQUANTITATIVE', 'QUALITATIVE', 'TITER', 'MULTI_CATALOG')), _negated=True), _connector='OR'), name='parameter_option_set_required_for_coded_types'), models.CheckConstraint(condition=models.Q(models.Q(('value_type', 'NUMERIC_CALCULATED'), _negated=True), models.Q(('formula', ''), _negated=True), _connector='OR'), name='parameter_formula_required_when_calculated')],
            },
        ),
    ]
