# Generated by Django 5.1.15 on 2026-09-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedoption',
            name='numeric_equivalent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Equivalente numérico'),
        ),
    ]
