# Generated by Django 5.1.15 on 2026-09-26 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_codedoption_numeric_equivalent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('ANY', 'Ambos')], default='ANY', max_length=3, verbose_name='Sexo')),
                ('age_min_days', models.PositiveIntegerField(default=0, verbose_name='Edad mínima (días)')),
                ('age_max_days', models.PositiveIntegerField(default=54750, verbose_name='Edad máxima (días)')),
                ('condition', models.CharField(choices=[('NINGUNA', 'Ninguna'), ('EMBARAZO', 'Embarazo'), ('AYUNO', 'Ayuno'), ('POST_PRANDIAL', 'Post-prandial')], default='NINGUNA', max_length=15, verbose_name='Condición')),
                ('range_type', models.CharField(choices=[('CLOSED', 'Rango cerrado'), ('UPPER_BOUND', 'Límite superior'), ('LOWER_BOUND', 'Límite inferior'), ('TOLERANCE', 'Tolerancia'), ('QUALITATIVE', 'Cualitativo'), ('INTERPRETIVE', 'Interpretativo')], max_length=15, verbose_name='Tipo de rango')),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Límite inferior')),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Límite superior')),
                ('center', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Centro')),
                ('tolerance', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Tolerancia')),
                ('bands', models.JSONField(blank=True, null=True, verbose_name='Bandas interpretativas')),
                ('display_text', models.CharField(max_length=255, verbose_name='Texto a imprimir')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridad (desempate)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('expected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.codedoption')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='catalog.parameter')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.unit')),
            ],
            options={
                'verbose_name': 'Rango de referencia',
                'verbose_name_plural': 'Rangos de referencia',
                'ordering': ['parameter', '-priority'],
                'constraints': [models.CheckConstraint(condition=models.Q(('age_min_days__lte', models.F('age_max_days'))), name='referencerange_age_min_lte_age_max'), models.CheckConstraint(condition=models.Q(models.Q(('range_type__in', ('CLOSED', 'LOWER_BOUND')), ('low__isnull', False)), models.Q(('range_type__in', ('CLOSED', 'LOWER_BOUND')), _negated=True), _connector='OR'), name='referencerange_low_required'), models.CheckConstraint(condition=models.Q(models.Q(('range_type__in', ('CLOSED', 'UPPER_BOUND')), ('high__isnull', False)), models.Q(('range_type__in', ('CLOSED', 'UPPER_BOUND')), _negated=True), _connector='OR'), name='referencerange_high_required'), models.CheckConstraint(condition=models.Q(models.Q(('range_type', 'TOLERANCE'), ('center__isnull', False), ('tolerance__isnull', False)), models.Q(('range_type', 'TOLERANCE'), _negated=True), _connector='OR'), name='referencerange_tolerance_requires_center_and_tolerance'), models.CheckConstraint(condition=models.Q(models.Q(('range_type', 'QUALITATIVE'), ('expected_option__isnull', False)), models.Q(('range_type', 'QUALITATIVE'), _negated=True), _connector='OR'), name='referencerange_qualitative_requires_expected_option'), models.CheckConstraint(condition=models.Q(models.Q(('range_type', 'INTERPRETIVE'), ('bands__isnull', False)), models.Q(('range_type', 'INTERPRETIVE'), _negated=True), _connector='OR'), name='referencerange_interpretive_requires_bands')],
            },
        ),
    ]
