# Generated by Django 5.1.15 on 2026-09-27 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_rangos_lipidos_sin_condicion_ayuno"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="container",
        ),
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "code",
                    models.CharField(max_length=30, unique=True, verbose_name="Código"),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Nombre")),
                (
                    "short_name",
                    models.CharField(
                        help_text="Lo que se imprime en la etiqueta: AZUL, ROJO, ORINA…",
                        max_length=12,
                        verbose_name="Nombre corto (etiqueta)",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#94a3b8",
                        help_text="Hexadecimal, p. ej. #2563eb",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "additive",
                    models.CharField(
                        choices=[
                            ("CITRATO", "Citrato de sodio"),
                            ("NINGUNO", "Sin aditivo / activador"),
                            ("GEL", "Gel separador"),
                            ("HEPARINA", "Heparina"),
                            ("EDTA", "EDTA"),
                            ("FLUORURO", "Fluoruro / oxalato"),
                            ("NO_APLICA", "No aplica (envase)"),
                        ],
                        max_length=12,
                        verbose_name="Aditivo",
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("SANGRE_TOTAL", "Sangre total"),
                            ("SUERO", "Suero"),
                            ("PLASMA", "Plasma"),
                            ("ORINA", "Orina"),
                            ("ORINA_24H", "Orina 24 horas"),
                            ("HECES", "Heces"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="Tipo de muestra",
                    ),
                ),
                (
                    "volume_ml",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="Volumen (mL)",
                    ),
                ),
                (
                    "draw_order",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="Orden de extracción"
                    ),
                ),
                (
                    "max_tests",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = sin límite.",
                        verbose_name="Máx. exámenes por tubo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tubo / envase",
                "verbose_name_plural": "Tubos y envases",
                "ordering": ["draw_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SampleRequirement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "collection_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sólo para tomas por tiempo: «Basal», «2 horas post-carga»…",
                        max_length=30,
                        verbose_name="Toma",
                    ),
                ),
                (
                    "own_container",
                    models.BooleanField(
                        default=False,
                        help_text="No compartir el tubo con otros exámenes.",
                        verbose_name="Tubo propio",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "container_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requirements",
                        to="catalog.containertype",
                        verbose_name="Tubo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_requirements",
                        to="catalog.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tubo requerido",
                "verbose_name_plural": "Tubos requeridos",
                "ordering": ["test", "order_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("test", "container_type", "collection_label"),
                        name="samplerequirement_unique",
                    )
                ],
            },
        ),
    ]
