# Generated by Django 5.1.15 on 2026-09-27 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_tubos_de_toma"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referencerange",
            name="critical_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Crítico alto",
            ),
        ),
        migrations.AddField(
            model_name="referencerange",
            name="critical_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Crítico bajo",
            ),
        ),
        migrations.AddField(
            model_name="referencerange",
            name="critical_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="P. ej. «PROPUESTO (literatura)» o «Confirmado por el laboratorio».",
                max_length=120,
                verbose_name="Origen de los críticos",
            ),
        ),
        migrations.CreateModel(
            name="ReagentLot",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "reagent",
                    models.CharField(
                        choices=[("TROMBOPLASTINA", "Tromboplastina (PT / INR)")],
                        max_length=20,
                        verbose_name="Reactivo",
                    ),
                ),
                ("lot_number", models.CharField(max_length=40, verbose_name="Lote")),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Marca"
                    ),
                ),
                (
                    "isi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="ISI",
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(blank=True, null=True, verbose_name="Vence"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Vigente"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de reactivo",
                "verbose_name_plural": "Lotes de reactivos",
                "ordering": ["reagent", "-is_current", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("reagent",),
                        name="reagentlot_single_current",
                    ),
                    models.UniqueConstraint(
                        fields=("reagent", "lot_number"), name="reagentlot_unique_lot"
                    ),
                ],
            },
        ),
    ]
